DROP TABLE IF EXISTS carspecs;
DROP TABLE IF EXISTS car_creators;
DROP TABLE IF EXISTS delivery;
DROP TABLE IF EXISTS car_orders;
DROP TABLE IF EXISTS car;

CREATE TABLE car (
ID INT(10) NOT NULL AUTO_INCREMENT,
CREATOR VARCHAR(20) NOT NULL,
MODEL VARCHAR(20) NOT NULL,
COUNTRY VARCHAR(20) NOT NULL,
PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE carspecs (
ID INT(10) NOT NULL AUTO_INCREMENT,
BODY VARCHAR(20) NOT NULL,
COLOR VARCHAR(20) NOT NULL,
ENGINE_SIZE INT(5) NOT NULL,
PRIMARY KEY (`ID`),
FOREIGN KEY (ID) REFERENCES car(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE car_creators (
WORKER_ID INT(10) NOT NULL AUTO_INCREMENT,
CAR_ID INT(10) NOT NULL,
NAME VARCHAR(20) NOT NULL,
SURNAME VARCHAR(20) NOT NULL,
PRIMARY KEY (`WORKER_ID`),
FOREIGN KEY (CAR_ID) REFERENCES car(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE car_orders (
ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
CAR_ID INT(10) NOT NULL,
COMMENTS VARCHAR(50) NOT NULL,
CITY VARCHAR(30) NOT NULL,
AMOUNT INT(5) NOT NULL,
PRIMARY KEY (`ORDER_ID`),
FOREIGN KEY (CAR_ID) REFERENCES car(ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE delivery (
ORDER_ID INT(10) NOT NULL AUTO_INCREMENT,
TYPE VARCHAR(20) NOT NULL,
PRIMARY KEY (`ORDER_ID`),
FOREIGN KEY (ORDER_ID) REFERENCES car_orders(ORDER_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
